# Generated by Django 4.2.7 on 2023-12-18 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_video_call_link_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_status',
            field=models.CharField(choices=[('Not Sent', 'Not Sent'), ('Sent', 'Sent')], default='Not Sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
