# Generated by Django 4.2.7 on 2023-12-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_consulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_link',
            field=models.URLField(blank=True, default='empty'),
        ),
        migrations.DeleteModel(
            name='Consulation',
        ),
    ]
