# Generated by Django 4.2.7 on 2024-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_video_link_delete_consulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Hospitalized', 'Hospitalized')], default='Pending', max_length=20),
        ),
    ]
