# Generated by Django 4.2.7 on 2023-12-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointments',
            field=models.ManyToManyField(related_name='patient_appointments', to='appointments.appointment'),
        ),
    ]
