# Generated by Django 4.2.7 on 2023-12-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_created_at_remove_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='doctor_profile_pics/default.png', upload_to='doctor_profile_pics/'),
        ),
    ]
